### ISSUE TITLE
Program pre-programmed paths (Path Mode)

### ISSUE THREAD

**Issue by PAOK-2001** [PAOK-2001/Clean-It#8]

**Comment by PacoRmzA** [comment]
Ideas:
- Empty room clean: The robot follows a simple, zig zag pattern (long forward, turn right, short forward, turn right, long forward, turn left, short forward, turn left, repeat) until it gets to the end of the room.
- Spill clean: The robot does an outward spiral, implemented with an increasing counter, so as to clean a specific area. It stops every roomba length or so to do a more thorough cleaning.
- Battery test: The robot goes forward indefinitely.
- Empty room deep clean: Same as first pattern, but with the stops mentioned in the second one.
- Room outline: The robot goes around the room, trying to minimize the measurement of the left proximity sensor and maximize the measurement of the right one. This is done to cover the areas that are usually dirtier after sweeping the floor.
